using System.Collections.Generic;
using System.IO;

namespace QRBuild
{
    internal sealed class BuildFile
    {
        public BuildFile(string path)
        {
            m_path = path;
        }

        public string Path
        {
            get { return m_path; }
        }

        /// The BuildNode that generates this Target.
        /// If null, this Target is not generated by any Translation
        /// in the parent BuildGraph.
        public BuildNode BuildNode;

        /// The set of all nodes that depend on this file.
        public readonly HashSet<BuildNode> Consumers = new HashSet<BuildNode>();

        readonly string m_path;     
    }
}
