using System.IO;

namespace QRBuild.Engine
{
    internal sealed class BuildFile
    {
        public BuildFile(string path)
        {
            m_path = path;
        }

        public string Path
        {
            get { return m_path; }
        }

        /// The BuildNode that generates this Target.
        /// If null, this Target is not generated by any Translation
        /// in the parent BuildGraph.
        public BuildNode BuildNode;

        readonly string m_path;
    }
}
