using System.IO;

namespace QRBuild.Engine
{
    internal sealed class BuildFile
    {
        public BuildFile(string id)
        {
            m_id = id;
        }

        public string Id
        {
            get { return m_id; }
        }

        public bool Exists()
        {
            return File.Exists(Id);
        }

        public void Clean()
        {
            File.Delete(Id);
        }

        /// The BuildNode that generates this Target.
        /// If null, this Target is not generated by any Translation
        /// in the parent BuildGraph.
        public BuildNode BuildNode;

        readonly string m_id;
    }
}
